import { Project, CanvasElement, Page, DeviceType, UIComponentVariant } from './types';

export const createDefaultElements = (pageId: string, templateType: string): CanvasElement[] => {
  if (templateType === 'onboarding') {
    return [
      // 1. Device frame representing a phone
      {
        id: `df-1`,
        type: 'device-frame',
        name: 'iPhone 15 Pro Frame',
        x: 420,
        y: 40,
        width: 360,
        height: 720,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 1,
        deviceType: 'iphone',
        backgroundColor: '#FFFFFF',
        orientation: 'portrait',
      },
      // Status & Header inside device
      {
        id: `text-1`,
        type: 'text',
        name: 'Title Text',
        x: 450,
        y: 130,
        width: 300,
        height: 70,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 2,
        text: 'Welcome to\nYour New Journey',
        fontFamily: 'Inter',
        fontSize: 26,
        fontWeight: 'bold',
        fontColor: '#0F172A',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'center',
        lineHeight: 1.3,
        letterSpacing: -0.5,
      },
      // Subtext inside device
      {
        id: `text-2`,
        type: 'text',
        name: 'Subtitle Text',
        x: 460,
        y: 215,
        width: 280,
        height: 50,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 3,
        text: 'Learn how to master your personal finance in three simple, guided steps.',
        fontFamily: 'Inter',
        fontSize: 13,
        fontWeight: 'normal',
        fontColor: '#64748B',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'center',
        lineHeight: 1.5,
        letterSpacing: 0,
      },
      // Graphic visual inside phone
      {
        id: `shape-c1`,
        type: 'circle',
        name: 'Accent Ring',
        x: 535,
        y: 290,
        width: 130,
        height: 130,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 4,
        fillColor: '#EFF6FF',
        strokeColor: '#3B82F6',
        strokeWidth: 2,
        strokeDasharray: '4 4',
      },
      {
        id: `shape-s1`,
        type: 'star',
        name: 'Accent Star',
        x: 575,
        y: 330,
        width: 50,
        height: 50,
        rotation: 15,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 5,
        fillColor: '#2563EB',
        strokeColor: '#1D4ED8',
        strokeWidth: 1,
        starPoints: 5,
      },
      // Form Input inside device
      {
        id: `input-1`,
        type: 'ui-component',
        componentType: 'input-text',
        name: 'Email Input Field',
        x: 460,
        y: 450,
        width: 280,
        height: 54,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 6,
        props: {
          label: 'Email Address',
          placeholder: 'alex@example.com',
          value: '',
        },
      },
      // Primary Action Button inside device
      {
        id: `btn-1`,
        type: 'ui-component',
        componentType: 'button-primary',
        name: 'CTA Button',
        x: 460,
        y: 520,
        width: 280,
        height: 46,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 7,
        props: {
          label: 'Get Started Free',
          color: '#2563EB',
        },
      },
      // Steppers / annotations outside the frame
      {
        id: `step-1`,
        type: 'step-indicator',
        name: 'Step Marker 1',
        x: 90,
        y: 130,
        width: 240,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 8,
        stepNumber: 1,
        title: 'Crisp Headline',
        description: 'Keep titles short to grab the user\'s immediate focus upon opening.',
        status: 'completed',
      },
      {
        id: `step-2`,
        type: 'step-indicator',
        name: 'Step Marker 2',
        x: 90,
        y: 310,
        width: 240,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 9,
        stepNumber: 2,
        title: 'Focal Visual',
        description: 'Highlight key product benefits with simple graphical motifs.',
        status: 'active',
      },
      {
        id: `step-3`,
        type: 'step-indicator',
        name: 'Step Marker 3',
        x: 90,
        y: 490,
        width: 240,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 10,
        stepNumber: 3,
        title: 'Clear Sign-up Action',
        description: 'Prompt user for email to complete frictionless registration.',
        status: 'inactive',
      },
      // Callout on Right
      {
        id: `callout-1`,
        type: 'callout',
        name: 'Tip Callout',
        x: 840,
        y: 280,
        width: 200,
        height: 100,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 11,
        text: 'Interactive prototype hotspot: Click Get Started in preview to advance.',
        pointerDirection: 'left',
        backgroundColor: '#2563EB',
        textColor: '#FFFFFF',
      },
      // Connectors
      {
        id: `conn-1`,
        type: 'connector',
        name: 'Connector 1',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        zIndex: 12,
        startElementId: 'step-1',
        endElementId: 'text-1',
        lineStyle: 'curved',
        strokeColor: '#2563EB',
        strokeWidth: 2,
        strokeDasharray: '4 4',
      },
      {
        id: `conn-2`,
        type: 'connector',
        name: 'Connector 2',
        x: 0,
        y: 0,
        width: 0,
        height: 0,
        rotation: 0,
        opacity: 1,
        locked: true,
        hidden: false,
        zIndex: 13,
        startElementId: 'step-2',
        endElementId: 'shape-c1',
        lineStyle: 'curved',
        strokeColor: '#2563EB',
        strokeWidth: 2,
        strokeDasharray: '4 4',
      },
    ];
  }

  if (templateType === 'dashboard') {
    return [
      // Browser Window
      {
        id: `df-browser`,
        type: 'device-frame',
        name: 'Browser Window',
        x: 80,
        y: 50,
        width: 1040,
        height: 680,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 1,
        deviceType: 'browser',
        backgroundColor: '#F8FAFC',
        orientation: 'landscape',
      },
      // Top Navigation Bar
      {
        id: `navbar-1`,
        type: 'ui-component',
        componentType: 'navbar',
        name: 'App Navbar',
        x: 95,
        y: 110,
        width: 1010,
        height: 52,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 2,
        props: {
          label: 'Acme Cloud Platform',
          sublabel: 'Production EU-West',
        },
      },
      // Metric Card 1: Total Revenue
      {
        id: `metric-1`,
        type: 'ui-component',
        componentType: 'metric-card',
        name: 'Revenue Metric Card',
        x: 105,
        y: 180,
        width: 235,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 3,
        props: {
          label: 'Total Revenue',
          value: '$124,592',
          sublabel: '+18.4% vs last month',
          badgeText: '+18.4%',
          color: '#10B981',
        },
      },
      // Metric Card 2: Active Users
      {
        id: `metric-2`,
        type: 'ui-component',
        componentType: 'metric-card',
        name: 'Users Metric Card',
        x: 360,
        y: 180,
        width: 235,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 4,
        props: {
          label: 'Monthly Active Users',
          value: '48,290',
          sublabel: '+12.1% from referrals',
          badgeText: '+12.1%',
          color: '#2563EB',
        },
      },
      // Metric Card 3: Conversion Rate
      {
        id: `metric-3`,
        type: 'ui-component',
        componentType: 'metric-card',
        name: 'Conversion Metric Card',
        x: 615,
        y: 180,
        width: 235,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 5,
        props: {
          label: 'Avg Conversion Rate',
          value: '4.85%',
          sublabel: '+0.6% this cycle',
          badgeText: '+0.6%',
          color: '#8B5CF6',
        },
      },
      // Metric Card 4: System Uptime
      {
        id: `metric-4`,
        type: 'ui-component',
        componentType: 'metric-card',
        name: 'Uptime Metric Card',
        x: 870,
        y: 180,
        width: 235,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 6,
        props: {
          label: 'System SLA Uptime',
          value: '99.98%',
          sublabel: 'Zero downtime recorded',
          badgeText: 'Optimal',
          color: '#059669',
        },
      },
      // Alert Banner
      {
        id: `alert-1`,
        type: 'ui-component',
        componentType: 'alert-banner',
        name: 'System Status Alert',
        x: 105,
        y: 320,
        width: 1000,
        height: 48,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 7,
        props: {
          label: 'System Maintenance Scheduled',
          sublabel: 'Upgrades planned for Sunday at 02:00 UTC with zero estimated downtime.',
          color: '#3B82F6',
        },
      },
      // Chart Card Container
      {
        id: `chart-container`,
        type: 'rectangle',
        name: 'Chart Container Panel',
        x: 105,
        y: 390,
        width: 650,
        height: 310,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 8,
        fillColor: '#FFFFFF',
        strokeColor: '#E2E8F0',
        strokeWidth: 1,
        cornerRadius: 8,
      },
      {
        id: `text-chart-label`,
        type: 'text',
        name: 'Chart Header',
        x: 125,
        y: 405,
        width: 300,
        height: 24,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 9,
        text: 'Real-Time Telemetry & Throughput',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        fontColor: '#0F172A',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
      },
      // Callout annotation
      {
        id: `callout-db`,
        type: 'callout',
        name: 'Performance Callout',
        x: 780,
        y: 420,
        width: 290,
        height: 110,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 10,
        text: '🔥 High-throughput analytics engine automatically aggregates regional metrics every 5 seconds.',
        pointerDirection: 'left',
        backgroundColor: '#2563EB',
        textColor: '#FFFFFF',
      },
      // Sticky Note
      {
        id: `sticky-1`,
        type: 'sticky',
        name: 'Release Note',
        x: 780,
        y: 550,
        width: 200,
        height: 140,
        rotation: -2,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 11,
        color: 'yellow',
        text: 'Review with Engineering Team:\n- Verify API quota\n- Enable dark mode theme\n- Connect Redis cache',
        author: 'Lead Architect',
      },
    ];
  }

  if (templateType === 'ecommerce') {
    return [
      // Mobile phone frame
      {
        id: `df-phone`,
        type: 'device-frame',
        name: 'iPhone 15 Frame',
        x: 420,
        y: 40,
        width: 360,
        height: 720,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 1,
        deviceType: 'iphone',
        backgroundColor: '#FFFFFF',
        orientation: 'portrait',
      },
      // Search Bar
      {
        id: `search-1`,
        type: 'ui-component',
        componentType: 'input-search',
        name: 'Product Search',
        x: 440,
        y: 110,
        width: 320,
        height: 42,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 2,
        props: {
          placeholder: 'Search sneakers, apparel...',
        },
      },
      // Product Image
      {
        id: `prod-img`,
        type: 'image',
        name: 'Product Mockup Image',
        x: 440,
        y: 170,
        width: 320,
        height: 220,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 3,
        url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80',
        brightness: 100,
        contrast: 100,
        saturation: 100,
        blur: 0,
        grayscale: 0,
      },
      // Product Title & Price
      {
        id: `prod-title`,
        type: 'text',
        name: 'Product Title',
        x: 440,
        y: 405,
        width: 320,
        height: 30,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 4,
        text: 'Nike Air VaporMax Flyknit',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: 'bold',
        fontColor: '#0F172A',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'left',
        lineHeight: 1.2,
        letterSpacing: 0,
      },
      {
        id: `prod-price`,
        type: 'text',
        name: 'Product Price',
        x: 440,
        y: 440,
        width: 150,
        height: 24,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 5,
        text: '$199.99',
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: 'bold',
        fontColor: '#2563EB',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'left',
        lineHeight: 1.0,
        letterSpacing: 0,
      },
      // Add to Cart Button
      {
        id: `btn-cart`,
        type: 'ui-component',
        componentType: 'button-primary',
        name: 'Add to Cart CTA',
        x: 440,
        y: 500,
        width: 320,
        height: 48,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 6,
        props: {
          label: '🛒 Add to Shopping Cart',
          color: '#0F172A',
        },
      },
      // Buy with 1-Click
      {
        id: `btn-pay`,
        type: 'ui-component',
        componentType: 'button-primary',
        name: 'Apple Pay CTA',
        x: 440,
        y: 560,
        width: 320,
        height: 48,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 7,
        props: {
          label: ' Pay Now',
          color: '#2563EB',
        },
      },
      // Mobile Tab Bar
      {
        id: `tabbar-1`,
        type: 'ui-component',
        componentType: 'tabbar',
        name: 'Bottom Tab Bar',
        x: 420,
        y: 690,
        width: 360,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 8,
        props: {
          label: 'Shop',
          sublabel: '4 Items in Cart',
        },
      },
      // Annotations
      {
        id: `step-e1`,
        type: 'step-indicator',
        name: 'Checkout Step 1',
        x: 80,
        y: 200,
        width: 260,
        height: 95,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 9,
        stepNumber: 1,
        title: 'High-Res Hero Gallery',
        description: 'Provide 360° product angles and interactive zoom on tap.',
        status: 'completed',
      },
      {
        id: `step-e2`,
        type: 'step-indicator',
        name: 'Checkout Step 2',
        x: 80,
        y: 480,
        width: 260,
        height: 95,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 10,
        stepNumber: 2,
        title: 'Instant 1-Click Checkout',
        description: 'Speed up checkout conversions by offering native Apple Pay.',
        status: 'active',
      },
    ];
  }

  if (templateType === 'api-guide') {
    return [
      // Terminal Frame
      {
        id: `df-term`,
        type: 'device-frame',
        name: 'Developer Terminal Frame',
        x: 80,
        y: 60,
        width: 680,
        height: 480,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 1,
        deviceType: 'terminal',
        backgroundColor: '#0F172A',
        orientation: 'landscape',
      },
      // Terminal code text
      {
        id: `term-code`,
        type: 'text',
        name: 'Terminal Script Output',
        x: 105,
        y: 120,
        width: 630,
        height: 380,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 2,
        text: `$ curl -X POST https://api.cloud.acme/v1/auth \\\n  -H "Content-Type: application/json" \\\n  -d '{"api_key": "sec_live_948fbc291"}'\n\nHTTP/2 200 OK\n{\n  "status": "authenticated",\n  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6...",\n  "expires_in": 3600,\n  "scope": ["read:metrics", "write:deployments"]\n}`,
        fontFamily: 'Space Mono',
        fontSize: 13,
        fontWeight: 'normal',
        fontColor: '#38BDF8',
        fontStyle: 'normal',
        textDecoration: 'none',
        align: 'left',
        lineHeight: 1.6,
        letterSpacing: 0,
      },
      // Keycap Shortcut Badge
      {
        id: `key-1`,
        type: 'keycap',
        name: 'CLI Shortcut',
        x: 800,
        y: 100,
        width: 280,
        height: 60,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 3,
        keys: ['⌘', 'Shift', 'C'],
        label: 'Quick Copy Curl Snippet',
      },
      // Callout
      {
        id: `call-api`,
        type: 'callout',
        name: 'JWT Bearer Callout',
        x: 800,
        y: 200,
        width: 280,
        height: 120,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 4,
        text: '🔑 Pass the returned JWT token in the Authorization: Bearer header for all subsequent API endpoints.',
        pointerDirection: 'left',
        backgroundColor: '#2563EB',
        textColor: '#FFFFFF',
      },
      // Step guides
      {
        id: `step-api-1`,
        type: 'step-indicator',
        name: 'Step 1 - Auth',
        x: 800,
        y: 350,
        width: 280,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 5,
        stepNumber: 1,
        title: 'Generate API Key',
        description: 'Create a read/write API key from Developer Console.',
        status: 'completed',
      },
      {
        id: `step-api-2`,
        type: 'step-indicator',
        name: 'Step 2 - Request Token',
        x: 800,
        y: 460,
        width: 280,
        height: 90,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 6,
        stepNumber: 2,
        title: 'Execute Curl POST',
        description: 'Send authenticated request to exchange for 1-hour session token.',
        status: 'active',
      },
    ];
  }

  if (templateType === 'settings') {
    return [
      // Tablet frame
      {
        id: `df-tab`,
        type: 'device-frame',
        name: 'iPad Pro Settings Frame',
        x: 180,
        y: 50,
        width: 840,
        height: 660,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 1,
        deviceType: 'ipad',
        backgroundColor: '#FFFFFF',
        orientation: 'landscape',
      },
      // User Profile Card
      {
        id: `user-card-1`,
        type: 'ui-component',
        componentType: 'user-card',
        name: 'User Profile Card',
        x: 220,
        y: 110,
        width: 760,
        height: 80,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 2,
        props: {
          label: 'Alex Rivera',
          sublabel: 'Lead Product Designer • alex.rivera@design.co',
          badgeText: 'Pro Plan',
        },
      },
      // Input 1: Full Name
      {
        id: `inp-name`,
        type: 'ui-component',
        componentType: 'input-text',
        name: 'Name Input',
        x: 220,
        y: 210,
        width: 360,
        height: 56,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 3,
        props: {
          label: 'Display Name',
          value: 'Alex Rivera',
        },
      },
      // Input 2: Email
      {
        id: `inp-email`,
        type: 'ui-component',
        componentType: 'input-text',
        name: 'Email Input',
        x: 620,
        y: 210,
        width: 360,
        height: 56,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 4,
        props: {
          label: 'Email Address',
          value: 'alex.rivera@design.co',
        },
      },
      // Switch 1: 2FA
      {
        id: `sw-2fa`,
        type: 'ui-component',
        componentType: 'toggle-switch',
        name: '2FA Toggle',
        x: 220,
        y: 290,
        width: 760,
        height: 54,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 5,
        props: {
          label: 'Two-Factor Authentication (2FA)',
          sublabel: 'Require an authenticator app code on each login.',
          isActive: true,
        },
      },
      // Switch 2: Notifications
      {
        id: `sw-notif`,
        type: 'ui-component',
        componentType: 'toggle-switch',
        name: 'Notifications Toggle',
        x: 220,
        y: 360,
        width: 760,
        height: 54,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 6,
        props: {
          label: 'Instant Push Notifications',
          sublabel: 'Receive realtime security and deployment alerts.',
          isActive: true,
        },
      },
      // Save Changes CTA
      {
        id: `btn-save-settings`,
        type: 'ui-component',
        componentType: 'button-primary',
        name: 'Save Button',
        x: 220,
        y: 440,
        width: 200,
        height: 44,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 7,
        props: {
          label: 'Save Changes',
          color: '#2563EB',
        },
      },
      // Hotspot Beacon
      {
        id: `hotspot-1`,
        type: 'hotspot',
        name: 'Security Hotspot',
        x: 880,
        y: 295,
        width: 32,
        height: 32,
        rotation: 0,
        opacity: 1,
        locked: false,
        hidden: false,
        zIndex: 8,
        label: 'Mandatory 2FA',
        pulseColor: '#2563EB',
      },
    ];
  }

  // Blank template is empty
  return [];
};

export type TemplatePresetId = 'onboarding' | 'dashboard' | 'ecommerce' | 'api-guide' | 'settings' | 'blank';

export const loadTemplate = (id: TemplatePresetId): Project => {
  const getTemplateMeta = (type: TemplatePresetId) => {
    switch (type) {
      case 'onboarding':
        return {
          name: 'Onboarding Guide',
          desc: 'A beautiful 3-step mobile onboarding showcase with annotations.',
          pageName: 'Mobile Onboarding',
          bgColor: '#F1F5F9',
        };
      case 'dashboard':
        return {
          name: 'Analytics Dashboard Guide',
          desc: 'SaaS metrics, KPI telemetry cards, and browser mockups.',
          pageName: 'Analytics Dashboard',
          bgColor: '#E2E8F0',
        };
      case 'ecommerce':
        return {
          name: 'Mobile E-Commerce Flow',
          desc: 'Product gallery, 1-click Apple Pay checkout, and mobile tab bar.',
          pageName: 'Product Checkout',
          bgColor: '#F8FAFC',
        };
      case 'api-guide':
        return {
          name: 'Developer API Guide',
          desc: 'Code terminal, JWT authentication walkthrough, and keycaps.',
          pageName: 'API Authentication',
          bgColor: '#0B0F19',
        };
      case 'settings':
        return {
          name: 'User Settings & Security',
          desc: 'User profile management, 2FA toggle switches, and security hotspots.',
          pageName: 'Account Settings',
          bgColor: '#F1F5F9',
        };
      default:
        return {
          name: 'My Mockup Project',
          desc: 'A fresh, blank canvas for wireframes and user guides.',
          pageName: 'Page 1',
          bgColor: '#FFFFFF',
        };
    }
  };

  const meta = getTemplateMeta(id);

  const defaultPage: Page = {
    id: 'page-1',
    name: meta.pageName,
    width: 1200,
    height: 800,
    backgroundColor: meta.bgColor,
    elements: createDefaultElements('page-1', id),
    isCover: true,
  };

  const project: Project = {
    id: `project-${Date.now()}`,
    name: meta.name,
    description: meta.desc,
    pages: [defaultPage],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  return project;
};
